"""
Quorum — Pydantic Data Models
All structured types for the trading pipeline.
"""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


# ─── Enums ─────────────────────────────────────────────────────

class AssetType(str, Enum):
    STOCK = "stock"
    CRYPTO = "crypto"

class TradeAction(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    SHORT = "short"
    COVER = "cover"

class Sentiment(str, Enum):
    VERY_BULLISH = "very_bullish"
    BULLISH = "bullish"
    NEUTRAL = "neutral"
    BEARISH = "bearish"
    VERY_BEARISH = "very_bearish"

class ApprovalStatus(str, Enum):
    AUTO_APPROVED = "auto_approved"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"


# ─── Analyst Reports ──────────────────────────────────────────

class AnalystReport(BaseModel):
    """Report generated by an individual analyst agent."""
    analyst_type: str
    ticker: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    summary: str
    sentiment: Sentiment
    confidence: float = Field(ge=0.0, le=1.0)
    key_findings: list[str] = Field(default_factory=list)
    raw_data: dict = Field(default_factory=dict)
    reasoning: str = ""


# ─── Debate States ─────────────────────────────────────────────

class DebateMessage(BaseModel):
    """Single message in a debate."""
    speaker: str
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)

class InvestmentDebateState(BaseModel):
    """State of the bull/bear investment debate."""
    bull_arguments: list[DebateMessage] = Field(default_factory=list)
    bear_arguments: list[DebateMessage] = Field(default_factory=list)
    round_count: int = 0
    judge_verdict: str = ""
    judge_confidence: float = 0.0
    investment_thesis: str = ""

class RiskDebateState(BaseModel):
    """State of the risk analysis debate."""
    aggressive_arguments: list[DebateMessage] = Field(default_factory=list)
    conservative_arguments: list[DebateMessage] = Field(default_factory=list)
    neutral_arguments: list[DebateMessage] = Field(default_factory=list)
    round_count: int = 0
    judge_verdict: str = ""
    recommended_position_size: float = 0.0


# ─── Trade Decision ───────────────────────────────────────────

class TradeSignal(BaseModel):
    """Final trade signal from the pipeline."""
    ticker: str
    asset_type: AssetType
    action: TradeAction
    confidence: float = Field(ge=0.0, le=1.0)
    entry_price: Optional[float] = None
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    position_size_pct: float = Field(ge=0.0, le=1.0, default=0.0, description="Kelly Criterion sized")
    reasoning: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class TradeRecord(BaseModel):
    """Persisted trade record in the database."""
    id: Optional[int] = None
    ticker: str
    asset_type: AssetType
    action: TradeAction
    quantity: float
    price: float
    confidence: float
    reasoning: str
    approval_status: ApprovalStatus = ApprovalStatus.PENDING
    pnl: Optional[float] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    executed_at: Optional[datetime] = None


# ─── Portfolio ─────────────────────────────────────────────────

class Position(BaseModel):
    """Current position in an asset."""
    ticker: str
    asset_type: AssetType
    quantity: float
    avg_entry_price: float
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    unrealized_pnl_pct: float = 0.0

class PortfolioState(BaseModel):
    """Current portfolio snapshot."""
    cash: float = 100000.0
    equity: float = 0.0
    total_value: float = 100000.0
    positions: list[Position] = Field(default_factory=list)
    daily_pnl: float = 0.0
    total_pnl: float = 0.0
    total_pnl_pct: float = 0.0
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ─── Performance Metrics ──────────────────────────────────────

class PerformanceMetrics(BaseModel):
    """Aggregate performance statistics."""
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_return: float = 0.0
    total_return_pct: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    max_drawdown_pct: float = 0.0
    avg_trade_pnl: float = 0.0
    best_trade: float = 0.0
    worst_trade: float = 0.0


# ─── Agent Confidence ─────────────────────────────────────────

class AgentAccuracy(BaseModel):
    """Tracks an agent's historical prediction accuracy."""
    agent_name: str
    total_predictions: int = 0
    correct_predictions: int = 0
    accuracy: float = 0.0
    weight: float = 1.0  # Adaptive weight based on accuracy
    last_updated: datetime = Field(default_factory=datetime.utcnow)


# ─── Pipeline State (for LangGraph) ──────────────────────────

class PipelineState(BaseModel):
    """Complete state flowing through the agent pipeline."""
    ticker: str
    asset_type: AssetType = AssetType.STOCK
    trade_date: str
    
    # Analyst reports (filled in parallel)
    market_report: Optional[AnalystReport] = None
    sentiment_report: Optional[AnalystReport] = None
    news_report: Optional[AnalystReport] = None
    fundamentals_report: Optional[AnalystReport] = None
    
    # Debate states
    investment_debate: Optional[InvestmentDebateState] = None
    risk_debate: Optional[RiskDebateState] = None
    
    # Final output
    trade_signal: Optional[TradeSignal] = None
    
    # Agent confidence weights
    agent_weights: dict[str, float] = Field(default_factory=dict)


# ─── WebSocket Messages ───────────────────────────────────────

class WSMessage(BaseModel):
    """WebSocket message envelope."""
    type: str  # "analysis_update", "trade_signal", "portfolio_update", "agent_reasoning"
    data: dict
    timestamp: datetime = Field(default_factory=datetime.utcnow)
